apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pipeline-cli-template
spec:
  templates:
    - name: run-cli
      inputs:
        parameters:
          - name: command
      container:
        image: pipeline-cli:latest
        imagePullPolicy: Never
        command: ["pipeline-cli"]
        args: ["{{inputs.parameters.command}}"]
